version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    groups:
      devcontainers:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    groups:
      docker:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ci"
    groups:
      ci:
        patterns:
          - "*"
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      dependencies:
        patterns:
          - "*"
