changelog:
  categories:
    - title: ✨ Exciting New Features
      labels:
        - 🚀enhancement
    - title: 🐛 Bug Fixes
      labels:
        - 🐛bug
    - title: 📖 Documentation
      labels:
        - 📝documentation
    - title: 🆙 Version Up
      labels:
        - dependencies
    - title: ✅ Test
      labels:
        - ✅test
    - title: 🏗️ Infrastructure
      labels:
        - 🏗️infrastructure
    - title: 🧰 Maintenance
      labels:
        - "*"
