name: Auto Assign

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  issues:
    types: opened
  pull_request:
    types: opened

permissions:
  issues: write
  pull-requests: write
  repository-projects: read

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
    - name: Auto-assign
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh pr edit ${{ github.event.number }} --add-assignee JamBalaya56562 --repo ${{ github.repository }}
