name: Auto Assign

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  issues:
    types: opened
  pull_request:
    types: opened

permissions:
  issues: write
  pull-requests: write
  repository-projects: read

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
    - name: Auto-assign Issue
      if: github.event_name == 'issues'
      run: gh pr edit ${{ github.event.number }} --add-assignee @me --repo ${{ github.repository }}

    - name: Auto-assign Pull Request
      if: github.event_name == 'pull_request'
      run: gh issue edit ${{ github.event.number }} --add-assignee @me --repo ${{ github.repository }}
