name: 💬 Comment on the pull request

on:
  workflow_call:
    inputs:
      comment:
        description: "Comment to add to the pull request"
        required: true
        type: string
      pr_number:
        description: "Pull request number"
        required: true
        type: string
      title:
        description: "Pull request title"
        required: true
        type: string

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: 💬 Add a comment
        uses: actions/github-script@v7
        env:
          COMMENT: ${{ inputs.comment }}
          PR_NUMBER: ${{ inputs.pr_number }}
          TITLE: ${{ inputs.title }}
          CONCLUSION: ${{ github.event.workflow_run.conclusion }}
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: process.env.PR_NUMBER,
            })
            const oldComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes(process.env.TITLE)
            })
            if (oldComment) {
              await github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: oldComment.id,
              })
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: process.env.PR_NUMBER,
                body: process.env.COMMENT
              })
              return
            }
            if (process.env.CONCLUSION === 'failure') {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: process.env.PR_NUMBER,
                body: process.env.COMMENT
              })
            }
